# Generated by Django 4.2.1 on 2023-05-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('AI', 'Artificial Intelligence'), ('CS', 'Computer Science'), ('IS', 'Information Systems'), ('DS', 'Decision Support'), ('IT', 'Information Technology')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')]),
        ),
    ]
