# Generated by Django 4.2.1 on 2023-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_student_department_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('GN', 'General'), ('AI', 'Artificial Intelligence'), ('CS', 'Computer Science'), ('IS', 'Information Systems'), ('DS', 'Decision Support'), ('IT', 'Information Technology')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Y', 'Active'), ('N', 'Not active')], default='Y', max_length=1),
        ),
    ]
